### ISSUE TITLE
Multiline JSON produces unescaped env var

### ISSUE THREAD

**Issue by zvictor** [compwright/dotenv-stringify#8]
This code:
```js
stringify({ JSON_MULTILINE: JSON.stringify({ a: 'b', c: 'd' }, null, 2) })
```

Produces:
```env
JSON_MULTILINE={
  \"a\": \"b\",
  \"c\": \"d\"
}
```

---

As you can see, an unescaped multi line env var is created, which should not be allowed

**Comment by compwright** [comment]
You shouldn't have any multi-line values in an ENV file. Multi-line environment variables are problematic for a variety of reasons. Don't do this.
